sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 7k8Uxdifrkr/avhCo29XqYipG9Ah7h8BuOQSRx0N5TbvwPm2Kk/BRpptYpVNGJXYPOAPyR+hbHUk3R9fokoWu2OOTZF+LkvbiOVnu8QbOukBdRd7iwcpIaGIWMMgl7dqp0QBnelnzC912F+Rh8YdB4lweV/YjkBfbLwVGxoD4c473emO5y4BM3CJFGe6R+i1WOLsDDcJ8esPTb9Q3LQbS4XHbRndRSyXCqx2+lBvcHs2OUFLEpbZYEVyfKq25G0a/vXp1FVjf/zu7bhvhixDHnIeukLlhf8+xxlcNIwMxf0oqM+H6k/skzFJHkXUa1WQD5N3eSL0Gas9IbgDD0UKgHZ4Wg2Z6JGUhyVriqOYnQ+dXHhql4BvOJifugjaqXz/d2GTS5IdZzK8Wh+o82Lb4ZFyUhAQCljeZ4Hqs4zjFfImfToqViVjoFs+IUdCzYS1YfQIQfvXoNxChiLZN9s9oe7XWAcp6IXBNtz3SRrnRs1ZV4RKGJWf/uRBHv1cK+UeZ4fISy6LNaEpWqxD1GKv3nMpiqiJJSGQ5lXOgRpmKUolHdsm0GX6LEWTOw9ZCowOb9QsdgZ+zsZ7Gg+FVsAEJfgG+HYDeW2SOC8saNVRFoBRbzHe3WhJRNz//lvFYowFrBZej+iCUa9kK8MNquvTnHeYjHhUAs+5kb7Y4S1lqXQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cleopatra-Volume-05_5477
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy